---
abstract: 'Extensible Configuration System'
author:
  - 'Sebastian Knapp <sk@computer-leipzig.com>'
build_requires:
  IO::String: 0
  Module::Build: 0.40
  Test::More: 0
  Test::Requires: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Shari-Conf
provides:
  Shari::Conf:
    file: lib/Shari/Conf.pm
    version: 0.02
requires:
  Config::General: 0
  Hash::Merge: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
